name: Python application with GitHub Actions

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make install

      - name: Lint with pyLint
        run: |
          make lint

      - name: Format code
        run: |
          make format

      - name: Run tests
        run: |
          # Retrieve the API key from the secret
          OPENAI_API_KEY=$OPENAI_API_KEY make test

        env:
          API_KEY: ${{ secrets.OPENAI_API_KEY }}
